=== Doozer-Dnepr/JavaCoreHomework/Oleksii_Ushakov/Module 8 - MultiThreading/Synchronization/src/main/resources/transfers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://www.w3schools.com"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="transfers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transaction" minOccurs='1' maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sender" type="xs:string"/>
                            <xs:element name="recipient" type="xs:string"/>
                            <xs:element name="value" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Doozer-Dnepr/JavaCoreHomework/Oleksii_Ushakov/Module 8 - MultiThreading/Synchronization/src/main/resources/transfers.xml
<?xml version="1.0"?>
<transfers xmlns="http://www.w3schools.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3schools.com transfers.xsd">

    <transaction>
        <sender>6408 5915 6212 2110</sender>
        <recipient>8138 4201 9222 5310</recipient>
        <value>1854</value>
    </transaction>

    <transaction>
        <sender>6881 0427 8058 9503</sender>
        <recipient>5993 0627 3645 3911</recipient>
        <value>5250</value>
    </transaction>

    <transaction>
        <sender>3729 3341 5827 5032</sender>
        <recipient>2244 8143 5786 1456</recipient>
        <value>2445</value>
    </transaction>

    <transaction>
        <sender>4650 6940 2573 3500</sender>
        <recipient>4568 1934 7241 5192</recipient>
        <value>5405</value>
    </transaction>

    <transaction>
        <sender>6949 6433 7147 6453</sender>
        <recipient>3957 6520 7097 2564</recipient>
        <value>3339</value>
    </transaction>

    <transaction>
        <sender>7741 9983 3658 7446</sender>
        <recipient>3623 6975 1984 6111</recipient>
        <value>6933</value>
    </transaction>

    <transaction>
        <sender>7741 9983 3658 7446</sender>
        <recipient>7741 9983 3658 7446</recipient>
        <value>6933</value>
    </transaction>

</transfers>
